// movie action
export const ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST'; 
export const ADD_MOVIE_TO_WATCHED = 'ADD_MOVIE_TO_WATCHED'; 
export const MOVE_TO_WATCHLIST = 'MOVE_TO_WATCHLIST';
export const REMOVE_FROM_WATCHED = 'REMOVE_FROM_WATCHED';
